---
title: "Untitled"
author: "Ignacio Luis Bastías"
date: "2024-10-15"
output: pdf_document
---

# Introducción al código

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

```{r atajos_r}

# Atajos de teclado en R:
  # Ctrl + Alt + I              = agrega un chunk
  # Ctrl + Shift + M            = " |> " 
  # Alt + -                     = " <- "
  # Ctrl + I                    = ajusta la tabulación
  # Ctrl + Shift + /            = ajusta los comentarios a varias líneas
  # Shift + Alt + flecha abajo  = duplica la linea

```


```{r librerias}

# Paquetes que van a usarse a lo largo de todo el código, habituales
if (!require('tidyverse')) install.packages('tidyverse'); library('tidyverse')
if (!require('readxl')) install.packages('readxl'); library('readxl')

# Paquetes específicos de este análisis
if (!require('sna')) install.packages('sna'); library('sna')

```

# Bases y limpieza

```{r carga_de_bases}

# Cargo las bases de inversiones realizadas a start-ups con headquarters ubicados en Argentina

inversiones_a_argentina <- read_excel(path = "bases/inversiones_a_argentina_corregido.xlsx",
                                      sheet = "final")

inversiones_de_argentina <- read_excel(path = "bases/inversiones_de_argentina_corregido.xlsx",
                                      sheet = "final")

# En los nombres de las columnas, reemplazo los espacios con "_" y todos los nombres pasan a minúscula

inversiones_a_argentina <- inversiones_a_argentina |> 
  rename_with(~ gsub(" ", "_", .x)) |> 
  rename_with(tolower)

inversiones_de_argentina <- inversiones_de_argentina |> 
  rename_with(~ gsub(" ", "_", .x)) |> 
  rename_with(tolower)

```

```{r bind_rows}

# Pego las tablas una después de la otra
inversiones_argentina <- inversiones_a_argentina |> 
  bind_rows(inversiones_de_argentina)

# Elimino las inversiones que están duplicadas
inversiones_argentina <- inversiones_argentina |> 
  unique() 

# Elimino los objetos que ya no uso
rm(inversiones_a_argentina, inversiones_de_argentina)

```



```{r inversiones_publicas}

# Armo el listado separado de inversiones secretas, donde no se identifica quién puso la plata
INVERSIONES_SECRETAS <- inversiones_argentina |> 
  filter(is.na(lead_investors) & is.na(investor_names))


# Me quedo con las inversiones que incluyen el nombre de algún inversor
inversiones_argentina <- inversiones_argentina |> 
  filter(!is.na(lead_investors) | !is.na(investor_names))

```


```{r listado_de_2_variables}

# Separo los inversores en columnas
inversiones_argentina <-  inversiones_argentina |> 
  select(organization_name, lead_investors, investor_names) |> 
  separate_wider_delim(cols = c(lead_investors, investor_names),
                       delim = ", ",
                       names_sep = "_",
                       too_few = "align_start")

# Pivoteo a lo largo y filtro los NA
inversiones_argentina <- inversiones_argentina |> 
  pivot_longer(cols = starts_with("lead_investors") |
                      starts_with("investor_names"),
               names_to = "new_tipo_de_inversor",
               values_to = "investor") |> 
  filter(!is.na(investor))

# Elimino los duplicados
inversiones_argentina <- inversiones_argentina |> 
  distinct(organization_name, investor)

```


```{r matriz_de_inversores}

# Armo la matriz de inversores, con cantidad de empresas invertidas en común

## Armo una matriz de inversores, sin start ups
matriz_a_medias <- inversiones_argentina |> 
  # Ordeno la tibble por inversor
  arrange(investor) |> 
  mutate(value = 1) |>
  # Pivoteo para que queden de columnas los nombres de los VC; y completo los espacios vacíos con 0
  pivot_wider(names_from = investor,
              values_from = value,
              values_fill = list(value = 0)) |>
  # Elimino los nombres de las start-ups, porque ya no es relevante
  select(-organization_name) |>
  as.matrix()

## Pongo los inversores en la columna de nombres; para eso, multiplico por la matriz transpuesta
matriz_inversores <- t(matriz_a_medias) %*% matriz_a_medias

# Elimino el objeto que ya no necesito
rm(matriz_a_medias)

```


```{r edgelist_de_inversores}

# Armo el edgelist de inversores, que incluye cuántas start-ups tienen en común estos inversores

## Recupero los nombres de los fondos como columna
edgelist_inversores <- matriz_inversores |> 
  as.data.frame() |> 
  rownames_to_column() |> 
  # Modifica el nombre de la columna y elimina el anterior nombre
  mutate("new_inversor_1" = rowname,
         .before = rowname,
         .keep = "unused")

## Pivoteo los nombres de los fondos
edgelist_inversores <- edgelist_inversores |> 
  as_tibble() |> 
  pivot_longer(cols = !new_inversor_1,
               names_to = "new_inversor_2",
               values_to = "new_SU_en_comun") |> 
  filter(new_SU_en_comun != 0) |> 
  filter(new_inversor_1 != new_inversor_2)

```


```{r adjacency_inversores}

# Armo la matriz de inversores, en estructura adjacency

## Los números mayores a 1 se transforman en 1
adjacency_inversores <- ifelse(matriz_inversores > 0, 1, 0)

# Elimino las matrices, que son grandes y ocupan bastante espacio
rm(matriz_inversores)

```

# Armado de la red

```{r red_desde_adjecency}

# Creamos el objeto network, a partir de la adjecency
adjacency_inversores <- network(adjacency_inversores)

#summary(adjacency_inversores)

```

```{r red_desde_edgelist}

edgelist_inversores_corto <- edgelist_inversores |> 
  arrange(desc(new_SU_en_comun)) |> 
  filter(new_SU_en_comun > 3)

# Creamos el objeto network, a partir de la edgelist
edgelist_inversores_corto <- network(edgelist_inversores_corto,
                                     matrix.type = "edgelist")

#summary(edgelist_inversores_corto)

```

```{r red_graficada}

# ¿Saldrá una red de esto?
plot(edgelist_inversores_corto,
     # Muestra etiquetas
     displaylabels = F,
     # No muestra flechas
     usearrows = F,
     # Impide que se superpongan los nombres
     jitter = T,
     # Dice que es interactivo pero no estaría cambiando nada
     #interactive = F,
     # Impide cajas en las etiquetas
     boxed.labels = F,
     # Agranda el tamaño de los círculos
     vertex.cex = 0.8,
     edge.lwd = (as.numeric(edgelist_inversores_corto%e%"new_SU_en_comun"))^1.4)

#methods(plot) ---- plot.network.default()

```

























-----------------------

```{r CHUNK_DE_PRUEBA, eval=FALSE, include=FALSE}

inversiones_argentina |> 
  count(investor) |> 
  View()

inversiones_argentina |> 
  filter(is.na(lead_investors) & is.na(investor_names)) |> 
  View()

```

